### PR TITLE
Ticket 49214: Expanding the wnprc billing module

### LINKED ISSUE #528: Secure Issue 49291: Expanding the wnprc billing module
Issue [49291](https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=49291)
[Spec](https://docs.google.com/document/d/1EVDGq8_ydHScxmwrZRqXBo4JtoljKl3dO99ENQMnwPA/edit#heading=h.bcr61ba681l)
Implementation on a 23.11 release

### Tasks
- [x] Investigate and scope out the details 
- [x] Investigate backwards compatibility
- [x] Q&As with client
- [x] Create a query for procedure charge id associations
- [x] Spec & Implementation plan
- [x] Implementation review @labkey-jeckels @ankurjuneja @labkey-martyp 
- [x] Schema updates - 1 hr
- [x] Calculate costs - 2 hrs
- [x] Refactor existing procedure query - 2 hrs
- [x] Process queries - 5 hrs
- [x] Test regression fixes - 3 hrs
- [x] Test updates - 3 hrs  
- [x] Validation - 2 hrs 
- [x] Refactor email notification - 2 hrs
- [x] Code Review - 1 hr @ankurjuneja @labkey-jeckels 
- [x] Code Review changes
- [x] TC Verify and merge 📌

### PR DESCRIPTION
**Pull request by labkey-bpatel**
#### Rationale
Currently, the WNPRC Billing module processes only one type of procedure (blood draws) for one type of group (animal care) during a billing run. All the other procedures are handled by manual entries via Misc. Charges.

In this PR, we enhance the Billing module to allow blood draws for more than one group, and also have capability to automate billing for other procedures, such as surgeries, etc. in the future. Note that some effort will still be required in order to capture additional procedures, but that effort should be minimal.

Spec [here](https://docs.google.com/document/d/1EVDGq8_ydHScxmwrZRqXBo4JtoljKl3dO99ENQMnwPA/edit).

#### Related Pull Requests
* https://github.com/LabKey/ehrModules/pull/756

#### Changes
* Refactor existing blood draws query and updates to handle procedure queries.
* Add a link to add customized procedure queries to the Finance portal.
* Billing notification updates.
* Test fixes and updates

#### Usage
- To add a new procedure to the Billing process:
1. Create a simple procedure query similar to 'bloodDrawsAdditionalTubesAnimalServices.sql' or 'bloodDrawsOneTubeAnimalServices.sql' - your procedure query should have the same column names as these blood draw queries.
2. From the Finance folder > click on 'Add Procedure Queries' link under Other > click on '+' to insert a new row: Add schema name for your procedure query, procedure query name (without the .sql), brief description describing your query, select Charge Id from the drop down that associates with this procedure > Submit.
Billing process will use data from this table to get data from the procedure query and calculate the cost (with and without the tier rates) and get other necessary columns for the invoiced items.

### CODE REVIEW

File: WNPRC_EHR/test/src/org/labkey/test/tests/wnprc_ehr/WNPRC_EHRTest.java [hunk 1]
```diff
@@ -1308,28 +1373,37 @@ private void viewBillingQueries()
...
-        log("Verify blood draws");
-        beginAt(String.format("query%s/executeQuery.view?schemaName=wnprc_billing&query.queryName=procedureFeeRates&query.param.StartDate=%s&query.param.EndDate=%s", PRIVATE_FOLDER_PATH, startDate, endDate));
-        DataRegionTable procedureFeeRates = new DataRegionTable("query", this);
-        expectedRowData = Arrays.asList(PROJECT_MEMBER_ID, "2011-09-27 09:30", "00640991", "acct101", "$13.00", "1", "0.3", "$13.00", " ");
-        actualRowData = procedureFeeRates.getRowDataAsText(0, "Id", "date", "project", "debitedAccount", "unitCost", "quantity", "tierRate", "totalCost", "performedby");
-        assertEquals("Wrong row data for Procedure Fee Rates/Blood Draws: ", expectedRowData, actualRowData);
-        assertEquals("Two rows should be displayed", procedureFeeRates.getDataRowCount(), 2);
+        goToBillingFolder();
+        log("Verify num. rows for 'blood draws with one tube'");
+        beginAt(String.format("query/%s/executeQuery.view?schemaName=wnprc_billing&query.queryName=bloodDrawsOneTubeAnimalServices&query.date~dategte=2011-09-01&query.date~datelte=2011-09-30", PRIVATE_FOLDER_PATH));
```
Comment (labkey-jeckels) [inline WNPRC_EHR/test/src/org/labkey/test/tests/wnprc_ehr/WNPRC_EHRTest.java]: Any value in doing these as select rows API calls instead? I don't love having long hard-coded URLs but obviously this approach works

File: primateid/resources/scripts/primateid/triggers.js [hunk 2]
```diff
@@ -68,11 +68,18 @@ exports.init = function (EHR) {
             filterArray: [LABKEY.Filter.create('participantid', row['participantid'], LABKEY.Filter.Types.EQUAL)],
             requiredVersion: 17.1,
             success: function (data) {
+
+                // Getting the participantId field is the normal case, but in auto-tests we need to grab the Id field
+                var participantid = row['participantid'];
+                if (!participantid) {
+                    participantid = row['Id'];
+                }
```
Comment (labkey-jeckels) [inline primateid/resources/scripts/primateid/triggers.js]:
```suggestion
                var participantid = row['participantid'] || row['Id'];
```

File: wnprc_billing/resources/queries/wnprc_billing/bloodDrawsOneTubeAnimalServices.sql [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+    CAST(num_tubes AS DOUBLE) AS quantity,
+    taskId,
+    performedby
+FROM studyLinked.BloodSchedule bloodSch
+WHERE
+    num_tubes = 1 AND
+    billedBy.value = 'a' AND
+    qcstate.publicdata = true
+
+UNION
```
Comment (labkey-jeckels) [inline wnprc_billing/resources/queries/wnprc_billing/bloodDrawsOneTubeAnimalServices.sql]: I don't understand why the UNION is here. If num_tubes=1 we return num_tubes (which will be 1) as the quantity. If num_tubes>1, we return 1 as the quantity. Can we collapse these, remove the `WHERE` and always return 1 as the quantity?

File: wnprc_billing/src/org/labkey/wnprc_billing/notification/WNPRCBillingNotificationProvider.java [hunk 4]
```diff
@@ -133,4 +142,158 @@ public List<StringBuilder> getAdditionalNotifications(User user)
...
+            additionalCategoryUrls.put(description, url.toString());
+        }
+    }
+
+    private ChargeInfo getChargeInfo(int chargeId, ArrayList<ChargeInfo> chargeInfoArrayList, Object date)
+    {
+        Date chargeDate = (Date) date;
+        List<ChargeInfo> chargeInfoList = chargeInfoArrayList.stream().filter(ci -> ci.getChargeId() == chargeId).toList();
+
+        if (chargeInfoList.size() == 1)
```
Comment (labkey-jeckels) [inline wnprc_billing/src/org/labkey/wnprc_billing/notification/WNPRCBillingNotificationProvider.java]: I don't think we need either of these `if` statements. The `for` loop on its own will behave identically.

**Review by labkey-jeckels — CHANGES_REQUESTED** [review]

File: wnprc_billing/resources/queries/wnprc_billing/bloodDrawsOneTubeAnimalServices.sql (hunk 3 above)
Comment (labkey-bpatel) [reply wnprc_billing/resources/queries/wnprc_billing/bloodDrawsOneTubeAnimalServices.sql]: Yeah i think this was me testing both cases individually initially and added them as a UNION here, missed to collapse into one in the end

File: wnprc_billing/src/org/labkey/wnprc_billing/notification/WNPRCBillingNotificationProvider.java (hunk 4 above)
Comment (labkey-bpatel) [reply wnprc_billing/src/org/labkey/wnprc_billing/notification/WNPRCBillingNotificationProvider.java]: yup, this was copilot code, which technically is correct so didn't put much thought into collapsing it further.

File: WNPRC_EHR/test/src/org/labkey/test/tests/wnprc_ehr/WNPRC_EHRTest.java (hunk 1 above)
Comment (labkey-bpatel) [reply WNPRC_EHR/test/src/org/labkey/test/tests/wnprc_ehr/WNPRC_EHRTest.java]: now using buildURL() instead which is used in the tests frequently

File: wnprc_billing/src/org/labkey/wnprc_billing/notification/WNPRCBillingNotificationProvider.java [hunk 5]
```diff
@@ -197,42 +197,38 @@ public void getAdditionalChargeCategoryInfo(User u, Container c, Date startDate,
...
             }
-            Map<String, Double> totalsMap = new HashMap<>();
-            totalsMap.put("total", (procedureRows.size()*1.00));
-            totalsMap.put("totalCost", totalCostPerCategory);
-            totalsByCategory.put(description, totalsMap);
-            ActionURL url = QueryService.get().urlFor(u, c, QueryAction.executeQuery, procedureSchema, procedureQuery);
+            Map<String, Object> categoryInfo = new HashMap<>();
+
+            // set total no. of rows per each charge category/procedure query
+            categoryInfo.put("total", (procedureRows.size() * 1.00));
```
Comment (labkey-jeckels) [inline wnprc_billing/src/org/labkey/wnprc_billing/notification/WNPRCBillingNotificationProvider.java]: I missed this before. Why is it multiplying by 1.00?

**Review by labkey-jeckels — APPROVED** [review]

File: wnprc_billing/src/org/labkey/wnprc_billing/notification/WNPRCBillingNotificationProvider.java (hunk 5 above)
Comment (labkey-bpatel) [reply wnprc_billing/src/org/labkey/wnprc_billing/notification/WNPRCBillingNotificationProvider.java]: Good question, i think that the notification displays everything with 2 decimal places, even an int, not really sure why, so keeping it consistent what's in place

Comment (labkey-jeckels) [reply wnprc_billing/src/org/labkey/wnprc_billing/notification/WNPRCBillingNotificationProvider.java]: This code isn't rendering to a string, so I don't see how there would be any difference between using `1.0`, `1.00`, or `1.0000000`. Something else must be responsible for the string formatting.

Comment (labkey-bpatel) [reply wnprc_billing/src/org/labkey/wnprc_billing/notification/WNPRCBillingNotificationProvider.java]: I've refactored this, so that line of code is no longer valid. In fact, it should be a total quantity, and not total no. of rows in the first place, so that was my bug.
